export const GET_MEMBERS = 'GET_MEMBERS';
export const ADD_MEMBER = 'ADD_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const MEMBERS_LOADING = 'MEMBERS_LOADING';
